version: "2"
services:

  anthias-server:
    image: ghcr.io/fabianvolkers/anthias-server:latest-x86
    environment:
      - MY_IP=${MY_IP}
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: always
    volumes:
      - resin-data:/data
      - /home/${USER}/.screenly:/data/.screenly
      - /home/${USER}/screenly_assets:/data/screenly_assets
      - /home/${USER}/screenly/static:/data/screenly/static
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      io.balena.features.supervisor-api: '1'

  anthias-viewer:
    image: ghcr.io/fabianvolkers/anthias-viewer:latest-x86
    mem_limit: ${VIEWER_MEMORY_LIMIT_KB}k
    depends_on:
      - anthias-server
    environment:
      - HOME=/data
      - PORT=80
      - NOREFRESH=1
      - LISTEN=anthias-nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    restart: always
    volumes:
      - resin-data:/data
      - /home/${USER}/.screenly:/data/.screenly
      - /home/${USER}/screenly_assets:/data/screenly_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      io.balena.features.supervisor-api: '1'

  anthias-websocket:
    image: ghcr.io/fabianvolkers/anthias-websocket:latest-x86
    depends_on:
      - anthias-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    restart: always
    volumes:
      - resin-data:/data
      - /home/${USER}/.screenly:/data/.screenly
      - /home/${USER}/screenly_assets:/data/screenly_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  anthias-celery:
    image: ghcr.io/fabianvolkers/anthias-celery:latest-x86
    depends_on:
      - anthias-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: always
    volumes:
      - resin-data:/data
      - /home/${USER}/.screenly:/data/.screenly
      - /home/${USER}/screenly_assets:/data/screenly_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      io.balena.features.supervisor-api: '1'

  redis:
    image: screenly/anthias-redis:latest-x86
    ports:
      - 127.0.0.1:6379:6379
    restart: always
    volumes:
      - redis-data:/var/lib/redis

  anthias-nginx:
    image: ghcr.io/fabianvolkers/anthias-nginx:latest-x86
    ports:
      - 80:80
    environment:
      - HOME=/data
    depends_on:
      - anthias-server
      - anthias-websocket
    restart: always
    volumes:
      - resin-data:/data:ro
      - /home/${USER}/.screenly:/data/.screenly:ro
      - /home/${USER}/screenly_assets:/data/screenly_assets:ro
      - /home/${USER}/screenly/static:/data/screenly/static:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  resin-data:
  redis-data:
  screenly-data:
